# Generated by Django 3.1.7 on 2021-03-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['user'], 'verbose_name': 'manager'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
    ]
