# Generated by Django 3.1.7 on 2021-03-29 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_auto_20210328_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_vmanager',
        ),
        migrations.CreateModel(
            name='VManager',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='venues.user')),
                ('venue', models.ManyToManyField(related_name='vmanager', to='venues.Venue')),
            ],
            options={
                'verbose_name': 'venue_manager',
                'ordering': ['user'],
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='venues.vmanager'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='venues.vmanager'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
