# Generated by Django 3.1.7 on 2021-04-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(default='media/images/logo-comune-milano.png', upload_to='images/'),
        ),
    ]
