# Generated by Django 3.1.7 on 2021-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0015_auto_20210402_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(default='/piippo.png', upload_to='images/'),
        ),
    ]
