# Generated by Django 3.1.7 on 2021-04-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0016_auto_20210402_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='image',
        ),
    ]
