# Generated by Django 3.1.7 on 2021-04-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0017_remove_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(default='logo-comune-milano.png', upload_to='images/'),
        ),
    ]
