# Generated by Django 3.1.7 on 2021-04-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_venue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('html_header', models.TextField()),
                ('html_body', models.TextField()),
                ('html_script', models.TextField()),
            ],
        ),
    ]
