# Generated by Django 3.1.7 on 2021-04-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0019_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='name',
        ),
    ]
