# Generated by Django 3.1.7 on 2021-04-02 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0021_auto_20210402_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='html_string',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
