# Generated by Django 3.1.7 on 2021-04-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0022_map_html_string'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
    ]
