# Generated by Django 3.1 on 2021-04-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0025_auto_20210407_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=300),
        ),
    ]
