# Generated by Django 3.1 on 2021-04-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0029_auto_20210413_2045'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['venue'], name='venues_even_venue_i_a25f97_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='venues_even_date_d51b76_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['title'], name='venues_even_title_60b0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['venue'], name='venues_news_venue_i_1d8da9_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['date'], name='venues_news_date_75da5c_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['title'], name='venues_news_title_006b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['name'], name='venues_venu_name_6dcdaa_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['category'], name='venues_venu_categor_17e67f_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['address'], name='venues_venu_address_dd9a8e_idx'),
        ),
    ]
